### ISSUE TITLE
Simplify the product/variation types

### ISSUE THREAD

**Issue by bojanz** [AcroMedia/commerce-demo#12]
Both bags and masks have 1 product each. Furthermore, they have 1 color attribute each (instead of sharing one). These 2 products showcase color selection.

Suggestion:
1) Create a "Color" attribute and assign it to Clothing.
2) Remake the 3 clothing products to have colors.
3) Remove the bag and mask product and variation types, along with the tote color / mask color attributes.

**Comment by MikeAcro** [comment]
Agreed. Not sure when I'll get to this, but I'll work it into some other planned content/config changes (including #14 ).

**Comment by MikeAcro** [comment]
Ok, with the content overhaul this has been changed some, masks and bags are no more. I ended up removing the color attribute altogether too. We opted to create separate product entities for each color instead of giving one product. This fills out the catalog better. An exception is the Custom Mason Jar, which is kind of a showcase product on its own and so has its own specific attributes for color.

I did add two different 'size' attributes - one for clothing (sm, md, lg), one for shoes (9, 10, 11). To go with the shoe sizing, I added a footwear product/variation.

All in all, we tried to add more content that uses these variations so that there is better representation.
