### ISSUE TITLE
Question about front end product views

### ISSUE THREAD

**Issue by MrPaulDriver** [AcroMedia/commerce-demo#18]
A small support request if I may.

I'm a bit confused by the catalog and featured product views. I see that you are using the product type teaser, however there is product variation stuff, such as the 'add to cart' button and variation image which is not displayed in the front end views. Are these items being being hidden somehow?

**Comment by MikeAcro** [comment]
Hey Paul,

We really only load up the variations so that we can get the product price for use in the product template. You can see what I mean here: https://github.com/AcroMedia/commerce-demo/blob/master/web/themes/custom/commerce_2_demo/templates/commerce/commerce-product.html.twig#L34

The rest is hidden because we're not printing everything out via {{ product.content }}.

**Comment by MikeAcro** [comment]
BTW, Paul, not sure if you're going to DrupalCon this year, but if you are, swing by our booth. :+1:

**Comment by MrPaulDriver** [comment]
Thanks for this Mike, I should have realised there was some twig doing it's stuff. Unfortunately I won't make it to DrupalCon but hope to catch up another time.
