### ISSUE TITLE
Error Druing install 

### ISSUE THREAD

**Issue by etron770** [AcroMedia/commerce-demo#28]
- Debian  Stretch (PHP 7.0 newest available version - I deleted composer.lock because of PHP 7.1 requirement message)
- Debian Stretch php 7.3  after new git clone and composer install
Both version with the same errors

The first error with composer install:
` Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2018-05-23/commerce_checkbox-same-as-billing_2852207_166.patch
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2018-10-31/2938760-20.patch`

The second error occured  after  *"Installed custom block **module"*

`Error
Status message
Honeypot installed successfully. Please configure Honeypot to protect your forms from spam bots.`

`The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">drupalorange_profile</em> have unmet dependencies: <em class="placeholder">block.block.footer_navigation (menu_block), block.block.views_block__blog_listing (views), comment.type.node_comment (comment), core.base_field_override.menu_link_content.menu_link_content.changed (menu_link_content), core.base_field_override.node.cta_homepage.path (path), core.entity_form_display.node.blog_post.default (comment, datetime, image, path), core.entity_form_display.node.cta_homepage.default (image, link, path), core.entity_form_display.node.image_gallery.default (image, path), core.entity_form_display.node.page.default (field_group, image, path, webform), core.entity_view_display.node.page.default (webform), core.entity_view_mode.taxonomy_term.full (taxonomy), editor.editor.html (ckeditor, editor), field.field.node.blog_post.field_blog_image (image), field.field.node.blog_post.field_post_date (datetime), field.field.node.cta_homepage.field_cta_link (link), language.content_settings.comment.node_comment (content_translation, language), language.content_settings.node.blog_post (language), metatag.metatag_defaults.403 (metatag), node.type.blog_post (menu_ui), pathauto.pattern.blog_posts (pathauto), pathauto.pattern.blog_taxonomy (ctools, taxonomy, pathauto), pathauto.pattern.taxonomy_default (taxonomy, pathauto), shortcut.set.default (shortcut), views.view.blog (datetime, views), views.view.comments_recent (comment, views), views.view.taxonomy_term (taxonomy, views)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core/lib/Drupal/Core/Config/UnmetDependenciesException.php).`

`Drupal\Core\Config\UnmetDependenciesException::create('drupalorange_profile', Array) (Line: 485)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'drupalorange_profile') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'drupalorange_profile') (Line: 150)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1663)
install_install_profile(Array) (Line: 709)
install_run_task(Array, Array) (Line: 584)
install_run_tasks(Array, NULL) (Line: 125)
install_drupal(Object) (Line: 44)`

**Comment by MikeAcro** [comment]
Hi there, thanks for reporting this.

The demo is a bit outdated at the moment. There have been some core and module updates since it was updated last, and I think that might be the cause of these issues. I'm hoping to have this demo back up to date within the next week or two.

The first patch issue is related to [this issue](https://www.drupal.org/project/commerce_shipping/issues/2852207). The patch file referenced needs to be updated to a newer version.

The "drupalorange_profile" mentioned in the second issue is an internal install profile we created at Acro Media for starting new ecommerce sites. Something must have changed in that which is causing errors. I'm not sure off hand, but I'll try and get that resolved with the next update.

**Comment by etron770** [comment]
Any news about the release date for fixing the bug?
Would very nice to have the demo installation

**Comment by MikeAcro** [comment]
Hi again,

Sorry, nothing yet. It hasn't been forgotten, but I've been busy with higher priority tasks. Hoping to make some progress on it again soon (this week or the next) as these other tasks drop off.

**Comment by etron770** [comment]
Thank you for the quick response 
Stay calm , a as workaround I did the installation until the failure during the Drupal installation process (The second error occured after *"Installed custom block *module")

Then I imported the database from the commerce-demo/dumps/

And it is working

**Comment by MikeAcro** [comment]
Great! Good to hear it.

**Comment by etron770** [comment]
Seems that the database does not match exactly to the composer version. There are some errors, but for a first view it is ok

**Comment by MikeAcro** [comment]
Ok, thanks for the tip. This _should_ be resolved then once I've done updates and export a new database. I'll try that first when I get to it, and then dig deeper if needed.

**Comment by nigelwhite** [comment]
I guess this will be sorted at the same time, but just to show my interest.... a related install issue.....
On $ composer install I get
[ErrorException] "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
I tried $ composer self-update but it makes no difference.
I don't really want to hack my composer settings as in -
"As a quick and dirty alternative, you can fix the error in that one file. Just replace "continue" with "break" (or maybe "continue 2") in /usr/share/php/Composer/DependencyResolver/RuleSetGenerator.php at line 286"
because I don't know what I'm doing.

BTW Thank you for your videos on Commerce 2. I've spent ages trying to configure it out of the box and I'm pretty stuck. Like you say, a working example of config will be really useful.

**Comment by nigelwhite** [comment]
Got it going. The solution to my issue was updating composer. I had to do this manually as per instructions at https://getcomposer.org/download. Thanks

**Comment by MikeAcro** [comment]
Glad to hear it @nigelwhite , thanks for reporting back with your solution. Also, as an alternative, there is a lighter weight [Commerce Demo module](https://www.drupal.org/project/commerce_demo) by the core maintainers of the Commerce module that is also a good example of some initial config.

**Comment by etron770** [comment]
@nigelwhite 
> Got it going. The solution to my issue was updating composer. 

does the demo really works including  the patches?
Are the products visible?

**Comment by etron770** [comment]
As I can see the view /products does not return any product:

There are no products to display.

**Comment by MikeAcro** [comment]
The product catalog results are generated with a Search api/Solr combination, so if you don't have that setup then that may be why you're not seeing any products? Individual product entities should still be available to view though. Do you see anything when you go to `yourside.com/product/adventure-begins-camping-mug`?

**Comment by etron770** [comment]
Yes the products are visible
What's Search api/Solr  I am the server Admin, is there anything missing at the Server?
Debian Stretch -  Apache2

**Comment by etron770** [comment]
Additional: Trying to activate the Solr Search Defaults to see the configuration the following error appears:
Content type article not found. Database Search Defaults module could not be installed.

**Comment by MikeAcro** [comment]
@etron770 Search API and Solr are what powers the product catalog. You can read about the [Search API](https://www.drupal.org/project/search_api) and [Solr](https://www.drupal.org/project/search_api_solr) modules. There is some documentation for setting up your Solr server on the Solr module page, but you can also Google how to do that.

You don't need the Database Search Defaults module as the database packaged with the demo site already has the server and index set up. You just need to get Solr running and reindex the product index. In Drupal, the admin area for Search API is in _configuration > search and metadata > search api_ (/admin/config/search/search-api). Once you have your Solr server running, you will have to go to this admin page and adjust the product **server** configuration to match the core you've created. Then, once you see that the status of the server as enabled, you will have to go into the **index's** View tab and reindex the products. This builds the catalogue.

**Comment by etron770** [comment]
The server needs java for the SOLR is there no other solution?

**Comment by MikeAcro** [comment]
Search API allows the use of a database instead of Solr, so you could go that route instead.  You would select the 'Add server' button within `admin/config/search/search-api` and choose database as the backend. You might be able to then edit the existing product server, change the server setting to your new one and then reindex it. I've never tried switching servers, but you could give that a shot. If it doesn't work, create a new product index and use the current one for reference.

**Comment by etron770** [comment]
Is there any uptdate for that issue? 
maybe it is fixed already? 
Kind regards Knut

**Comment by etron770** [comment]
It is workin now as expected using  commerce-demo/README.md :
...
Option B: Local dev environment

Requirements

    Composer
....
