### ISSUE TITLE
Demo installation failed. Need help.

### ISSUE THREAD

**Issue by weeliem** [AcroMedia/commerce-demo#31]
Hi, i follow the installation step but ended up on this issue (Print screen). Any ideas what had happen?

PHP version: 7.3.5

[http://prntscr.com/nxauts](http://prntscr.com/nxauts)

**Comment by weeliem** [comment]
An issue happen when i import the demo database, the batch table caused the mysql server has gone away. Even i adjusted the setting in my mysql server. Anyone can help?

**Comment by MikeAcro** [comment]
If you're seeing the installation screen it would probably be because the imported database isn't being used. Make sure to update the `settings.php` or 'settings.local.php` with the information where you imported the provided database.

```
$databases['default']['default'] = array(
  'driver' => 'mysql',
  'host' => 'localhost',
  'username' => 'your_database_username',
  'password' => 'your_database_password',
  'database' => 'your_database_name',
  'prefix' => '',
);
```
If you're still seeing the installation screen after that, check your file and directory permissions. [This help doc](https://www.drupal.org/docs/7/install/step-3-create-settingsphp-and-the-files-directory) gives some more information about that. It's for Druapl 7 but would still be the same for Drupal 8.

For your second comment, I'm not quite sure what you mean.

**Comment by MikeAcro** [comment]
Oh wait. 

After looking at that screenshot again, it IS seeing the database. You just need to view your site. I suspect you got that when you went to `yoursite.com/install.php`? You shouldn't need to do that since the site is already installed once you've imported the database. Just visit your site url.

**Comment by weeliem** [comment]
Thanks, i am able to make the demo works after i tune the innodb_log_file_size slightly larger.

**Comment by MikeAcro** [comment]
Great, good to know. Thanks for reporting back.
